### ISSUE TITLE
Does not work for overridden methods

### ISSUE THREAD

**Issue by SEnglishSMP** [someguy20336/PullThroughDoc#1]
If I have an object that overrides a base class method or property (e.g. ToString), it would be nice to pull through the documentation from the base class method or property.

**Comment by someguy20336** [comment]
Just to clarify, are you trying to pull through the documentation from a class _outside_ of your solution?  I am assuming you are, considering your "Object.ToString" method example, but I just wanted to double check.

It should pull through the documentation for overridden members, but it might just not be working for when the class is outside of your solution.  Did you try it for a case when you defined both the base and derived class in the same project?

**Comment by someguy20336** [comment]
Closed as expected behavior (at least for now).
