### ISSUE TITLE
Upgrade to support 2022

### ISSUE THREAD

**Issue by someguy20336** [someguy20336/PullThroughDoc#13]
Follow [this guide](https://docs.microsoft.com/en-us/visualstudio/extensibility/migration/update-visual-studio-extension?view=vs-2022#msdynttrid=YcxdPeOrl8MEtWIAKmeHsuiAyAOyV6_sOtstfNlL9yQ)

**Comment by bsivanov** [comment]
It should be relatively straight-forward to add support for 2022 in the general case, especially if you don't want to support versions older than 2017 (which it seems you doesn't). Are you open for a PR on this? Or you can take a look at this if it helps: https://github.com/bsivanov/Open-XML-Package-Editor-Power-Tool-for-Visual-Studio/pull/4/files.

**Comment by someguy20336** [comment]
I am definitely open for a PR if you would want to knock it out!  I don't intend to try to keep supporting 2017 anymore.

The _only_ reason i have done this yet is because we aren't yet using VS 2022 at my work yet... So I haven't quite needed to upgrade it. 

If you don't do it, I might be interested in looking more into it within the next few weeks or so.

**Comment by someguy20336** [comment]
I think i just knocked this out today.  Going to publish it later today and merge in the code when everything seems to succeed.

**Comment by bsivanov** [comment]
Haha, just working on this, but OK! It seems the only needed change is to add 
```xml
        <InstallationTarget Id="Microsoft.VisualStudio.Community" Version="[17.0, 18.0)">
            <ProductArchitecture>amd64</ProductArchitecture>
        </InstallationTarget>
```
in the `.vsixmanifest`. 

I think you should also consider distributing this as a nuget package, as this is the [preferred method for analyzers](https://docs.microsoft.com/en-us/visualstudio/code-quality/roslyn-analyzers-overview?view=vs-2022#:~:text=If%20you%20install%20the%20analyzers%20as%20a%20NuGet%20package%2C%20which%20is%20the%20preferred%20method). This way you would have distribution independent of the Visual Studio versions as well.

**Comment by someguy20336** [comment]
haha sorry about that - I thought I might as well learn today after finally downloading VS 2022.  That was the same change I made, including a few more cleanup things (#14)

A nuget package sounds like a good idea.  It seems like there might be merit to one or both (i.e. "all the time" vs "just for this project"), but I think i need to read up a bit more on it.  Possibly include it in the PR or save it for a separate one.

**Comment by someguy20336** [comment]
Either way - published the VSIX v1.4.1.  It should probably be accepted within the next couple of hours, so it should be available later today.

**Comment by bsivanov** [comment]
It's already published, and I just verified it's working on my side. Thanks!

**Comment by someguy20336** [comment]
fantastic.  I was also able to install and verify it works.

I made a separate issue for the NuGet package (#15).  I am sure it is also pretty simple so maybe within the next few weeks.

**Comment by someguy20336** [comment]
FYI - in case you weren't watching #15, just deployed this as a NuGet package (#17).  Let me know if you have problems or something.
