### ISSUE TITLE
#region lines get copied and overwritten

### ISSUE THREAD

**Issue by Hefaistos68** [someguy20336/PullThroughDoc#3]
When you have comments right below #region pragmas in the source, they get copied when pulling through, and if you have them in the target, they get overwritten.
My guess is that the extension only scans for square brackets as comment termination.

example:
```
#region Testline
/// <summary>this comment will copy the region above when pulled through</summary>
```

**Comment by someguy20336** [comment]
Should be fixed in version 1.2
