### ISSUE TITLE
Problem with virtual property not being pulled through

### ISSUE THREAD

**Issue by Hefaistos68** [someguy20336/PullThroughDoc#4]
The comments of virtual properties are not available to pull through.

**Comment by someguy20336** [comment]
Virtual properties are supported, but only if the base class is located in your solution.  I suspect you are trying to pull through something like "Object.ToString()" where the base class is not located in your solution.

I do not currently support pulling that through because Roslyn does not have that documentation in the model.  I would need to manually look up the xml, which I haven't gotten to yet.

I will keep this open as a good enhancement if I ever get to it.

**Comment by Hefaistos68** [comment]
Actually I an seeing that on classes in the same project with properties from base classes in the solution.

**Comment by someguy20336** [comment]
Interesting... Can you give a little more details?  I definitely have a passing unit test for this exact scenario, so there must be something else at play here:

https://github.com/someguy20336/PullThroughDoc/blob/master/PullThroughDoc/PullThroughDoc.Test/PullThroughDocUnitTests.cs#L200

**Comment by someguy20336** [comment]
ooooooooooh wait - PROPERTIES and not methods?  I think i misread this whole thing... let me look into that...

**Comment by someguy20336** [comment]
Ok, I think I still need more information about your setup.  Properties seem to work just fine for me (i tried both public and protected).  In your project, how are the classes related to each other in the project structure?

Maybe some sample code would help too.

**Comment by Hefaistos68** [comment]
Will check whats the relation of the classes here. But its all in the same project (C# 8, .Net Core), give me a day to find out, its not happening with all properties in just any class.

**Comment by someguy20336** [comment]
Did you ever get a chance to look at this?  Could this just be the same issue we just made #9 ?

**Comment by Hefaistos68** [comment]
I am testing here with a larger project I am working on, i remember that this was not a constant problem but rather limited to some classes. Since this project uses practically none of the .NET classes to derive of, I think its not related to the other issue.
So far I could not repro it, maybe either the last version fixed it, or i didnt test the right situation. Keep you posted.
