### ISSUE TITLE
Use of optional inheritdoc tag

### ISSUE THREAD

**Issue by Hefaistos68** [someguy20336/PullThroughDoc#5]
Would be nice if it would be possible to either "pull through" the documentation or insert an "< inheritdoc / >" tag instead. And of course, where ever and inheritdoc tag is, replace it with the pull through documentation.

**Comment by someguy20336** [comment]
Great idea - in reality, I wonder if that is just what this tool should do now - just insert that tag.  For some reason, i just remember that never seeming to work in Visual studio, but just tested it out and it seemed to work fine.

But i suppose there could be value in having both, but maybe `<inheritdoc/>` should be the default now?  Thoughts?

**Comment by Hefaistos68** [comment]
It does really work well, but often a pull through is more appropriate, because you need to either modify the original or just add something.
Personally I'd like to see it as an option, maybe a default to set or a second menu entry.

**Comment by someguy20336** [comment]
Cool, i like it.  Implemented inserting `inheritdoc`, but now looking at the whole "switch between them" thing next

**Comment by someguy20336** [comment]
fixed in #6

**Comment by Hefaistos68** [comment]
Very nice, works like a charm. Especially the "change to" is really useful.
